### ISSUE TITLE
Issue after upgrading to 1.11

### ISSUE THREAD

**Issue by zonArt** [jenkinsci/stashnotifier-plugin#128] opened 2016-09-16 13:57 UTC
We're currently facing a strange issue after upgrading to version 1.11. Looks like that for some weird reason, when you save your job configuration through the UI adding the "Notify Stash Instance" as "Add post-build action", you get the whole jenkins configuration setup within the configuration of the stashnotifier-plugin. Like that
```
    <org.jenkinsci.plugins.stashNotifier.StashNotifier plugin="stashNotifier@1.11">
      <stashServerBaseUrl>stash_url</stashServerBaseUrl>
      <credentialsId></credentialsId>
      <ignoreUnverifiedSSLPeer>false</ignoreUnverifiedSSLPeer>
      <commitSha1></commitSha1>
      <includeBuildNumberInKey>false</includeBuildNumberInKey>
      <projectKey></projectKey>
      <prependParentProjectKey>false</prependParentProjectKey>
      <disableInprogressNotification>false</disableInprogressNotification>
CONTENT OF <jenkins_home>/config.xml
    </org.jenkinsci.plugins.stashNotifier.StashNotifier>
```

Did anyone noticed something similar ?
We're using jenkins-1.651.1

**Comment by scaytrase** [comment] 2016-09-16 17:04
Duplicate of #125. Not released yet, though. I'll hope I can do it this weekend

**Closed by scaytrase** 2016-09-16 17:04 UTC

**Comment by zonArt** [comment] 2016-09-16 17:42
Sorry for the duplicate, sure it looks exactly similar, I should have better checked

**Comment by scaytrase** [comment] 2016-09-16 17:46
Not a problem, issue was not addressed on issues list, only on pull requests

**Comment by scaytrase** [comment] 2016-09-16 18:42
Realeased as [1.11.4](https://github.com/jenkinsci/stashnotifier-plugin/releases/tag/1.11.4)
