### ISSUE TITLE
Use plugin on Jenkins 2.0 multibranch pipeline

### ISSUE THREAD

**Issue by tmds** [jenkinsci/stashnotifier-plugin#106] opened 2016-05-11 09:39 UTC
I don't know how to setup the plugin on a multibranch pipeline.
The configuration page does not have a 'Post-build Actions section'.

**Comment by scaytrase** [comment] 2016-05-11 11:00
Duplicate of #92

**Closed by scaytrase** 2016-05-11 11:00 UTC

**Comment by marcusphi** [comment] 2016-06-03 11:07
To me it seems like the Bitbucket (Stash) notofocation is automatic when using the bitbucket branch source plugin for the multibranch pipeline.

**Comment by tmds** [comment] 2016-06-03 23:35
@marcusphi I didn't know about that plugin. Can you set it up to use a local stash/bitbucket server as well?

**Comment by marcusphi** [comment] 2016-06-04 07:25
Yes. The Bitbucket server URL is configurable.

Marcus Philip
+46 70 767 46 77
Twitter: @marcus_phi
